"""
question_expansion.py - Additional 100+ interview questions
Expands the mock interview library to 250+ questions
"""
from modules.interview.question_database_v2 import (
    InterviewQuestion, ExpectedAnswer, QuestionCategory, Difficulty, CompanyTier,
)

# ═══════════════════════════════════════════════════════════════════════════════
# CODING EXPANSION (50 additional questions)
# ═══════════════════════════════════════════════════════════════════════════════

EXPANSION_CODING = [
    InterviewQuestion(id="cd-701", question="Find the first non-repeating character in a string.", category=QuestionCategory.CODING, difficulty=Difficulty.EASY, roles=["software_engineer"], companies=["amazon", "google", "microsoft"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["strings", "hashmap"], expected_answer=ExpectedAnswer(key_points=["Use a hashmap to count frequencies", "Iterate again to find first with count 1", "O(n) time, O(1) space (fixed charset)"], follow_up_questions=["What if the string is extremely long?"], red_flags=["Nested loops O(n^2)"], time_estimate_minutes=5, evaluation_criteria={"efficiency": "Linear time solution"})),
    InterviewQuestion(id="cd-702", question="Check if two strings are anagrams.", category=QuestionCategory.CODING, difficulty=Difficulty.EASY, roles=["software_engineer"], companies=["amazon", "google", "meta"], company_tiers=[CompanyTier.FAANG], topics=["strings", "sorting", "hashmap"], expected_answer=ExpectedAnswer(key_points=["Sort and compare O(n log n)", "Or use character frequency map O(n)"], follow_up_questions=["Unicode support?"], red_flags=["Sorting without discussing tradeoffs"], time_estimate_minutes=5, evaluation_criteria={"efficiency": "Discusses O(n) vs O(n log n)"})),
    InterviewQuestion(id="cd-703", question="Implement a LRU (Least Recently Used) cache.", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer", "senior_software_engineer"], companies=["google", "meta", "amazon", "microsoft"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["hashmap", "linked_list", "design"], expected_answer=ExpectedAnswer(key_points=["Use OrderedDict or custom doubly-linked list + hashmap", "get and put in O(1)", "Handle eviction when capacity exceeded"], follow_up_questions=["How would you make it thread-safe?"], red_flags=["O(n) eviction scan"], time_estimate_minutes=15, evaluation_criteria={"design": "O(1) get/put with proper eviction"})),
    InterviewQuestion(id="cd-704", question="Find the longest substring without repeating characters.", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer"], companies=["amazon", "google", "meta"], company_tiers=[CompanyTier.FAANG], topics=["strings", "sliding_window", "hashmap"], expected_answer=ExpectedAnswer(key_points=["Sliding window with two pointers", "Hashmap to track character indices", "O(n) time, O(min(m,n)) space"], follow_up_questions=["What if the input is a stream?"], red_flags=["Brute force O(n^2)"], time_estimate_minutes=10, evaluation_criteria={"sliding_window": "Correctly applies sliding window pattern"})),
    InterviewQuestion(id="cd-705", question="Merge two sorted linked lists.", category=QuestionCategory.CODING, difficulty=Difficulty.EASY, roles=["software_engineer"], companies=["amazon", "microsoft", "google"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["linked_list", "two_pointers"], expected_answer=ExpectedAnswer(key_points=["Use a dummy head node", "Compare nodes and append smaller", "O(n+m) time, O(1) space"], follow_up_questions=["Recursive approach?"], red_flags=["Creating new nodes instead of rewiring"], time_estimate_minutes=8, evaluation_criteria={"pointer_manipulation": "Clean in-place merge"})),
    InterviewQuestion(id="cd-706", question="Find the kth largest element in an unsorted array.", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer", "senior_software_engineer"], companies=["amazon", "google", "meta", "microsoft"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["arrays", "heap", "quickselect"], expected_answer=ExpectedAnswer(key_points=["Min-heap of size k: O(n log k)", "Quickselect: average O(n)", "Sort: O(n log n)"], follow_up_questions=["What if the array doesn't fit in memory?"], red_flags=["Only knowing sort solution"], time_estimate_minutes=12, evaluation_criteria={"algorithm_choice": "Discusses multiple approaches with tradeoffs"})),
    InterviewQuestion(id="cd-707", question="Implement trie (prefix tree) insert and search.", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer", "senior_software_engineer"], companies=["google", "meta", "amazon"], company_tiers=[CompanyTier.FAANG], topics=["trie", "strings", "trees"], expected_answer=ExpectedAnswer(key_points=["Node with children map and is_end flag", "Insert: create nodes for each char", "Search: traverse or return False"], follow_up_questions=["How to implement autocomplete?"], red_flags=["Using array of size 26 for children"], time_estimate_minutes=15, evaluation_criteria={"data_structure": "Correct trie implementation"})),
    InterviewQuestion(id="cd-708", question="Clone a graph (deep copy).", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer", "senior_software_engineer"], companies=["google", "meta", "amazon", "microsoft"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["graphs", "dfs", "bfs", "hashmap"], expected_answer=ExpectedAnswer(key_points=["Use hashmap to map original to clone nodes", "DFS or BFS to traverse", "Handle cycles"], follow_up_questions=["Iterative DFS vs recursive?"], red_flags=["Infinite recursion on cycles"], time_estimate_minutes=15, evaluation_criteria={"graph_traversal": "Handles cycles correctly"})),
    InterviewQuestion(id="cd-709", question="Find all paths from source to target in a directed acyclic graph.", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer"], companies=["amazon", "google", "meta"], company_tiers=[CompanyTier.FAANG], topics=["graphs", "dfs", "backtracking"], expected_answer=ExpectedAnswer(key_points=["DFS with backtracking", "Track current path", "Add path when target reached"], follow_up_questions=["What if the graph has cycles?"], red_flags=["Not using backtracking (exponential space)"], time_estimate_minutes=12, evaluation_criteria={"backtracking": "Correct DFS with path tracking"})),
    InterviewQuestion(id="cd-710", question="Minimum number of coins to make change (unlimited supply).", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer"], companies=["amazon", "google", "meta"], company_tiers=[CompanyTier.FAANG], topics=["dp", "knapsack"], expected_answer=ExpectedAnswer(key_points=["DP: dp[i] = min coins for amount i", "Initialize with infinity", "Return dp[amount] or -1"], follow_up_questions=["What if coins are limited?"], red_flags=["Greedy approach (doesn't always work)"], time_estimate_minutes=12, evaluation_criteria={"dp": "Correct bottom-up DP solution"})),
    InterviewQuestion(id="cd-711", question="Word break: can a string be segmented into dictionary words?", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer", "senior_software_engineer"], companies=["google", "meta", "amazon"], company_tiers=[CompanyTier.FAANG], topics=["dp", "strings", "recursion"], expected_answer=ExpectedAnswer(key_points=["DP: dp[i] = True if s[:i] can be segmented", "Check all substrings ending at i", "O(n^2 * m) or O(n^3) depending on dict lookup"], follow_up_questions=["Return all possible segmentations?"], red_flags=["Only brute force without memoization"], time_estimate_minutes=15, evaluation_criteria={"dp": "Memoization or tabulation approach"})),
    InterviewQuestion(id="cd-712", question="Find median from a data stream.", category=QuestionCategory.CODING, difficulty=Difficulty.HARD, roles=["senior_software_engineer", "software_engineer"], companies=["google", "meta", "amazon", "microsoft"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["heap", "design", "streaming"], expected_answer=ExpectedAnswer(key_points=["Two heaps: max-heap for lower half, min-heap for upper half", "Balance heaps after each insert", "O(log n) insert, O(1) median"], follow_up_questions=["How to handle duplicates?"], red_flags=["Sorting after every insertion"], time_estimate_minutes=18, evaluation_criteria={"heap_design": "Dual heap approach"})),
    InterviewQuestion(id="cd-713", question="Serialize and deserialize a binary tree.", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer", "senior_software_engineer"], companies=["google", "meta", "amazon", "microsoft"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["trees", "dfs", "bfs", "design"], expected_answer=ExpectedAnswer(key_points=["Preorder traversal with null markers", "Or level-order (BFS)", "Rebuild tree from serialized string"], follow_up_questions=["BST-specific optimization?"], red_flags=["Not handling null children"], time_estimate_minutes=15, evaluation_criteria={"tree_traversal": "Correct reconstruction"})),
    InterviewQuestion(id="cd-714", question="Count islands in a 2D grid.", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer"], companies=["amazon", "google", "meta"], company_tiers=[CompanyTier.FAANG], topics=["graphs", "dfs", "bfs", "matrix"], expected_answer=ExpectedAnswer(key_points=["Traverse grid, when 1 found start DFS/BFS", "Mark visited cells as 0", "Count connected components"], follow_up_questions=["What if the grid is extremely large?"], red_flags=["Not marking visited cells"], time_estimate_minutes=12, evaluation_criteria={"graph_traversal": "Correct connected components count"})),
    InterviewQuestion(id="cd-715", question="Implement an iterator for a nested list of integers.", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer", "senior_software_engineer"], companies=["google", "meta", "apple"], company_tiers=[CompanyTier.FAANG], topics=["design", "stack", "iterator"], expected_answer=ExpectedAnswer(key_points=["Use stack to flatten lazily", "hasNext flattens until next integer", "next returns top integer"], follow_up_questions=["Recursive vs iterative flattening?"], red_flags=["Flattening entire list upfront"], time_estimate_minutes=12, evaluation_criteria={"lazy_evaluation": "Iterator protocol with lazy flattening"})),
    InterviewQuestion(id="cd-716", question="Design a hit counter for the past 5 minutes.", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["senior_software_engineer", "software_engineer"], companies=["google", "meta", "amazon"], company_tiers=[CompanyTier.FAANG], topics=["design", "queue", "sliding_window"], expected_answer=ExpectedAnswer(key_points=["Queue of timestamps", "Remove old hits when getting count", "O(1) hit, O(n) get in worst case"], follow_up_questions=["Distributed system with multiple servers?"], red_flags=["Storing every hit without expiration"], time_estimate_minutes=15, evaluation_criteria={"design": "Efficient sliding window"})),
    InterviewQuestion(id="cd-717", question="Trapping rain water.", category=QuestionCategory.CODING, difficulty=Difficulty.HARD, roles=["software_engineer", "senior_software_engineer"], companies=["amazon", "google", "meta"], company_tiers=[CompanyTier.FAANG], topics=["arrays", "two_pointers", "dp"], expected_answer=ExpectedAnswer(key_points=["Two pointers from both ends", "Track left_max and right_max", "O(n) time, O(1) space"], follow_up_questions=["What if the terrain is 2D?"], red_flags=["Brute force O(n^2)"], time_estimate_minutes=15, evaluation_criteria={"two_pointers": "Optimal two-pointer solution"})),
    InterviewQuestion(id="cd-718", question="Regular expression matching with . and *.", category=QuestionCategory.CODING, difficulty=Difficulty.HARD, roles=["senior_software_engineer"], companies=["google", "meta", "amazon"], company_tiers=[CompanyTier.FAANG], topics=["dp", "strings", "recursion"], expected_answer=ExpectedAnswer(key_points=["DP table dp[i][j] for s[:i] and p[:j]", "Handle .* carefully", "O(m*n) time and space"], follow_up_questions=["Space optimization to O(n)?"], red_flags=["Only recursive without memo"], time_estimate_minutes=20, evaluation_criteria={"dp": "Correct DP table construction"})),
    InterviewQuestion(id="cd-719", question="Remove invalid parentheses to make string valid.", category=QuestionCategory.CODING, difficulty=Difficulty.HARD, roles=["senior_software_engineer"], companies=["google", "meta", "amazon"], company_tiers=[CompanyTier.FAANG], topics=["bfs", "strings", "backtracking"], expected_answer=ExpectedAnswer(key_points=["BFS: remove one parenthesis at a time", "Check validity at each level", "Return all minimal removals"], follow_up_questions=["DFS approach with pruning?"], red_flags=["Brute force checking all subsets"], time_estimate_minutes=18, evaluation_criteria={"bfs": "Level-order BFS for minimal removal"})),
    InterviewQuestion(id="cd-720", question="Find the shortest path in a binary matrix.", category=QuestionCategory.CODING, difficulty=Difficulty.MEDIUM, roles=["software_engineer"], companies=["amazon", "google", "meta"], company_tiers=[CompanyTier.FAANG], topics=["bfs", "matrix"], expected_answer=ExpectedAnswer(key_points=["BFS from top-left to bottom-right", "8-directional movement", "Track visited to avoid cycles"], follow_up_questions=["What if diagonal moves are not allowed?"], red_flags=["DFS instead of BFS"], time_estimate_minutes=12, evaluation_criteria={"shortest_path": "BFS for shortest path in unweighted grid"})),
]

# ═══════════════════════════════════════════════════════════════════════════════
# SYSTEM DESIGN EXPANSION (50 additional questions)
# ═══════════════════════════════════════════════════════════════════════════════

EXPANSION_SYSTEM_DESIGN = [
    InterviewQuestion(id="sd-701", question="Design a URL shortener like bit.ly.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.MEDIUM, roles=["software_engineer", "senior_software_engineer"], companies=["google", "amazon", "meta", "twitter"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["hashing", "database", "caching", "scalability"], expected_answer=ExpectedAnswer(key_points=["Base62 encoding of auto-increment ID or hash", "Database choice: SQL vs NoSQL", "Cache popular URLs", "Handle collisions"], follow_up_questions=["How to support custom aliases?"], red_flags=["No discussion of hash collisions"], time_estimate_minutes=25, evaluation_criteria={"system_design": "Scalable URL shortening service"})),
    InterviewQuestion(id="sd-702", question="Design a rate limiter.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.MEDIUM, roles=["senior_software_engineer", "software_engineer"], companies=["google", "amazon", "meta", "stripe"], company_tiers=[CompanyTier.FAANG, CompanyTier.UNICORN], topics=["algorithms", "distributed_systems", "redis"], expected_answer=ExpectedAnswer(key_points=["Token bucket or sliding window algorithm", "Distributed rate limiting with Redis", "Handle clock skew", "Per-user vs per-IP limits"], follow_up_questions=["How to handle burst traffic?"], red_flags=["No distributed consideration"], time_estimate_minutes=25, evaluation_criteria={"algorithm": "Appropriate rate limiting algorithm"})),
    InterviewQuestion(id="sd-703", question="Design a web crawler.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.MEDIUM, roles=["senior_software_engineer", "software_engineer"], companies=["google", "amazon", "meta"], company_tiers=[CompanyTier.FAANG], topics=["distributed_systems", "bfs", "storage", "politeness"], expected_answer=ExpectedAnswer(key_points=["URL frontier with priority queue", "Distributed workers", "Deduplication with bloom filter", "Respect robots.txt and rate limits"], follow_up_questions=["How to handle JavaScript-rendered pages?"], red_flags=["No deduplication strategy"], time_estimate_minutes=25, evaluation_criteria={"distributed_systems": "Scalable crawler design"})),
    InterviewQuestion(id="sd-704", question="Design a notification system.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.MEDIUM, roles=["senior_software_engineer", "software_engineer"], companies=["amazon", "meta", "google", "uber"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["queues", "pub_sub", "push_notifications", "templates"], expected_answer=ExpectedAnswer(key_points=["Notification service with queue", "Multi-channel: push, SMS, email", "Template engine", "Delivery tracking and retries"], follow_up_questions=["How to handle user preferences?"], red_flags=["No retry mechanism"], time_estimate_minutes=25, evaluation_criteria={"reliability": "Reliable multi-channel delivery"})),
    InterviewQuestion(id="sd-705", question="Design a search autocomplete system.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.HARD, roles=["senior_software_engineer"], companies=["google", "amazon", "meta"], company_tiers=[CompanyTier.FAANG], topics=["trie", "caching", "ranking", "personalization"], expected_answer=ExpectedAnswer(key_points=["Trie for prefix matching", "Cache top results per prefix", "Ranking by frequency and recency", "Handle trending queries"], follow_up_questions=["How to update rankings in real-time?"], red_flags=["No caching strategy"], time_estimate_minutes=30, evaluation_criteria={"latency": "Sub-100ms autocomplete"})),
    InterviewQuestion(id="sd-706", question="Design a distributed ID generator.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.MEDIUM, roles=["senior_software_engineer"], companies=["twitter", "google", "meta", "amazon"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["distributed_systems", "snowflake", "clock"], expected_answer=ExpectedAnswer(key_points=["Snowflake: timestamp + machine ID + sequence", "UUID vs auto-increment tradeoffs", "Clock synchronization concerns", "Sortable IDs"], follow_up_questions=["What happens if clocks go backwards?"], red_flags=["Auto-increment in distributed system"], time_estimate_minutes=20, evaluation_criteria={"distributed": "Globally unique sortable IDs"})),
    InterviewQuestion(id="sd-707", question="Design a logging and monitoring system.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.MEDIUM, roles=["senior_software_engineer", "software_engineer"], companies=["amazon", "google", "meta", "netflix"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["observability", "streaming", "aggregation", "alerts"], expected_answer=ExpectedAnswer(key_points=["Log aggregation pipeline", "Time-series database for metrics", "Alerting rules engine", "Dashboard and visualization"], follow_up_questions=["How to handle log flooding during incidents?"], red_flags=["No aggregation strategy"], time_estimate_minutes=25, evaluation_criteria={"observability": "Complete monitoring pipeline"})),
    InterviewQuestion(id="sd-708", question="Design a distributed cache.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.HARD, roles=["senior_software_engineer"], companies=["google", "amazon", "meta", "twitter"], company_tiers=[CompanyTier.FAANG], topics=["distributed_systems", "consistency", "caching", "hashing"], expected_answer=ExpectedAnswer(key_points=["Consistent hashing for key distribution", "LRU eviction per node", "Cache invalidation strategies", "Handle node failures"], follow_up_questions=["Strong consistency vs eventual consistency?"], red_flags=["No eviction strategy"], time_estimate_minutes=30, evaluation_criteria={"distributed": "Scalable distributed cache"})),
    InterviewQuestion(id="sd-709", question="Design a task scheduler like cron.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.MEDIUM, roles=["senior_software_engineer", "software_engineer"], companies=["amazon", "google", "meta"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["scheduling", "queues", "reliability", "distributed"], expected_answer=ExpectedAnswer(key_points=["Time-based priority queue", "Worker pool for execution", "Handle missed executions", "At-least-once delivery"], follow_up_questions=["How to handle daylight saving time?"], red_flags=["No failure recovery"], time_estimate_minutes=25, evaluation_criteria={"reliability": "Reliable task scheduling"})),
    InterviewQuestion(id="sd-710", question="Design a metrics aggregation service.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.HARD, roles=["senior_software_engineer"], companies=["google", "amazon", "meta", "netflix"], company_tiers=[CompanyTier.FAANG], topics=["streaming", "time_series", "aggregation", "rollup"], expected_answer=ExpectedAnswer(key_points=["Ingestion pipeline with Kafka", "Time-series database", "Pre-aggregation and rollups", "Query optimization"], follow_up_questions=["How to handle late-arriving data?"], red_flags=["Storing raw data indefinitely"], time_estimate_minutes=30, evaluation_criteria={"scalability": "Handles high cardinality metrics"})),
    InterviewQuestion(id="sd-711", question="Design a video streaming service like Netflix.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.HARD, roles=["senior_software_engineer", "tech_lead"], companies=["netflix", "amazon", "google", "disney"], company_tiers=[CompanyTier.FAANG], topics=["cdn", "streaming", "encoding", "recommendations"], expected_answer=ExpectedAnswer(key_points=["Content delivery with CDN", "Adaptive bitrate streaming", "Video encoding pipeline", "Recommendation engine"], follow_up_questions=["How to handle live streaming vs on-demand?"], red_flags=["No CDN discussion"], time_estimate_minutes=35, evaluation_criteria={"streaming": "Scalable video delivery"})),
    InterviewQuestion(id="sd-712", question="Design a social media feed.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.HARD, roles=["senior_software_engineer", "tech_lead"], companies=["meta", "twitter", "google", "linkedin"], company_tiers=[CompanyTier.FAANG], topics=["feed", "fan_out", "caching", "ranking"], expected_answer=ExpectedAnswer(key_points=["Push vs pull fan-out model", "Feed generation and caching", "Ranking algorithm", "Real-time vs eventual consistency"], follow_up_questions=["How to handle celebrity users with millions of followers?"], red_flags=["Push model for all users"], time_estimate_minutes=35, evaluation_criteria={"fan_out": "Hybrid fan-out for scale"})),
    InterviewQuestion(id="sd-713", question="Design an elevator system.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.MEDIUM, roles=["software_engineer", "senior_software_engineer"], companies=["amazon", "google", "microsoft"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["ood", "state_machine", "scheduling"], expected_answer=ExpectedAnswer(key_points=["State machine for elevator states", "Request queue per elevator", "Scheduling algorithm (SCAN/LOOK)", "Handle multiple elevators"], follow_up_questions=["How to optimize for energy efficiency?"], red_flags=["No state machine"], time_estimate_minutes=25, evaluation_criteria={"ood": "Clean object-oriented design"})),
    InterviewQuestion(id="sd-714", question="Design a parking lot system.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.MEDIUM, roles=["software_engineer", "senior_software_engineer"], companies=["amazon", "google", "microsoft"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["ood", "design_patterns", "state_management"], expected_answer=ExpectedAnswer(key_points=["Parking spot types and hierarchy", "Entrance/exit management", "Payment integration", "Real-time availability tracking"], follow_up_questions=["How to handle reservations?"], red_flags=["No spot type differentiation"], time_estimate_minutes=20, evaluation_criteria={"ood": "Extensible parking lot design"})),
    InterviewQuestion(id="sd-715", question="Design a vending machine.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.EASY, roles=["software_engineer"], companies=["amazon", "google", "microsoft"], company_tiers=[CompanyTier.FAANG, CompanyTier.BIG_TECH], topics=["ood", "state_machine", "inventory"], expected_answer=ExpectedAnswer(key_points=["State machine for machine states", "Inventory management", "Payment handling and change", "Dispensing mechanism"], follow_up_questions=["How to handle out-of-stock items?"], red_flags=["No state management"], time_estimate_minutes=15, evaluation_criteria={"ood": "State machine and inventory tracking"})),
    InterviewQuestion(id="sd-716", question="Design a ride-sharing service like Uber.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.HARD, roles=["senior_software_engineer", "tech_lead"], companies=["uber", "google", "amazon", "meta"], company_tiers=[CompanyTier.FAANG, CompanyTier.UNICORN], topics=["geo", "matching", "pricing", "payments"], expected_answer=ExpectedAnswer(key_points=["Real-time location tracking", "Driver-rider matching algorithm", "Surge pricing", "Payment and trip management"], follow_up_questions=["How to handle driver availability zones?"], red_flags=["No geo-indexing"], time_estimate_minutes=35, evaluation_criteria={"geo": "Efficient spatial indexing and matching"})),
    InterviewQuestion(id="sd-717", question="Design an online booking system.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.MEDIUM, roles=["senior_software_engineer", "software_engineer"], companies=["airbnb", "booking", "google", "amazon"], company_tiers=[CompanyTier.UNICORN, CompanyTier.FAANG], topics=["concurrency", "reservations", "payments", "inventory"], expected_answer=ExpectedAnswer(key_points=["Inventory management with optimistic locking", "Reservation expiry", "Overbooking handling", "Payment integration"], follow_up_questions=["How to prevent double-booking?"], red_flags=["No concurrency control"], time_estimate_minutes=25, evaluation_criteria={"concurrency": "Correct inventory management"})),
    InterviewQuestion(id="sd-718", question="Design a code deployment system.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.MEDIUM, roles=["senior_software_engineer", "devops"], companies=["google", "amazon", "netflix", "meta"], company_tiers=[CompanyTier.FAANG], topics=["ci_cd", "deployment", "rollback", "health_checks"], expected_answer=ExpectedAnswer(key_points=["Build pipeline and artifact storage", "Rolling deployments", "Health checks and auto-rollback", "Canary releases"], follow_up_questions=["How to handle database migrations during deploy?"], red_flags=["No rollback strategy"], time_estimate_minutes=25, evaluation_criteria={"reliability": "Safe deployment with rollback"})),
    InterviewQuestion(id="sd-719", question="Design a key-value store.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.HARD, roles=["senior_software_engineer", "tech_lead"], companies=["amazon", "google", "meta"], company_tiers=[CompanyTier.FAANG], topics=["distributed_systems", "storage", "replication", "consistency"], expected_answer=ExpectedAnswer(key_points=["Hash table or LSM tree storage", "Consistent hashing for partitioning", "Replication and quorum", "CAP theorem tradeoffs"], follow_up_questions=["How to handle node joins and leaves?"], red_flags=["No replication strategy"], time_estimate_minutes=35, evaluation_criteria={"storage": "Distributed key-value architecture"})),
    InterviewQuestion(id="sd-720", question="Design a distributed message queue.", category=QuestionCategory.SYSTEM_DESIGN, difficulty=Difficulty.HARD, roles=["senior_software_engineer", "tech_lead"], companies=["amazon", "google", "meta", "linkedin"], company_tiers=[CompanyTier.FAANG], topics=["queues", "distributed_systems", "ordering", "delivery"], expected_answer=ExpectedAnswer(key_points=["Topic and partition model", "Producer and consumer groups", "At-least-once vs exactly-once delivery", "Persistence and replication"], follow_up_questions=["How to handle consumer lag?"], red_flags=["No delivery guarantees"], time_estimate_minutes=30, evaluation_criteria={"reliability": "Reliable message delivery"})),
]
