# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# React Native architecture
# Enable the new architecture (Fabric + TurboModules) — RN 0.73 default
newArchEnabled=true
hermesEnabled=true

# Kotlin
kotlin.code.style=official
