apiVersion: v2
name: ant-backend
description: AI Note Taker Backend API
type: application
version: 1.0.0
appVersion: "1.0"
kubeVersion: ">=1.24.0-0"

keywords:
  - ai
  - transcription
  - interview

maintainers:
  - name: ANT Team

dependencies:
  - name: common
    version: "2.x.x"
    repository: "https://charts.bitnami.com/bitnami"
