"""
Test suite for the Alembic migration setup.

Covers:
- Migration file structure (upgrade/downgrade/revision identifiers).
- `alembic upgrade head` creates all 13 model tables + `alembic_version`.
- `alembic downgrade base` drops everything except the version table.
- Re-upgrade roundtrip works.
- Idempotency: running upgrade twice is a no-op (no new SQL emitted).
- `DatabaseManager.initialize` runs alembic and stamps the version table.
- `ANT_SKIP_ALEMBIC=1` bypasses alembic (legacy `create_all` path).
- `migrations/env.py` resolves the DB URL from env vars and imports the
  project's `Base.metadata` from `core.database` for autogenerate support.

Run with: python -m pytest backend/tests/test_alembic_migrations.py -v
"""

import os
import re
import sqlite3
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

# Add backend/ to sys.path so we can import core.database and run alembic.
BACKEND_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_DIR))


# ---------------------------------------------------------------------------
# Migration file structure
# ---------------------------------------------------------------------------

class TestMigrationFileStructure:
    """The autogenerated migrations have the right shape."""

    def setup_method(self):
        # Locate the ROOT migration under versions/ (the one whose
        # `down_revision` is None). Multiple migrations can coexist
        # (e.g. f78f0efa440e → c391192d16be → a1b2c3d4e5f6); this
        # test class targets only the root, since that's the one
        # responsible for creating the 13 model tables.
        versions_dir = BACKEND_DIR / "migrations" / "versions"
        candidates = sorted(versions_dir.glob("*.py"))
        assert len(candidates) >= 1, "No migration files found in versions/"
        # Find the root migration: down_revision is None.
        root = None
        for path in candidates:
            text = path.read_text()
            if re.search(
                r"^down_revision:\s*Union\[str,\s*Sequence\[str\],\s*None\]\s*=\s*None",
                text, re.M,
            ):
                root = path
                break
        assert root is not None, "No root migration (down_revision=None) found"
        self.migration_file = root
        self.text = self.migration_file.read_text()

    def test_migration_has_revision_identifier(self):
        # `revision: str = '...'` line
        match = re.search(r"^revision:\s*str\s*=\s*'([a-f0-9]+)'", self.text, re.M)
        assert match is not None, "Migration has no `revision: str = '...'` line"  # nosec B101
        # Alembic revision IDs are 12 hex chars
        rev_id = match.group(1)
        assert len(rev_id) == 12  # nosec B101
        assert all(c in "0123456789abcdef" for c in rev_id)  # nosec B101

    def test_migration_is_root(self):
        # This is the FIRST migration, so down_revision must be None.
        match = re.search(
            r"^down_revision:\s*Union\[str,\s*Sequence\[str\],\s*None\]\s*=\s*None",
            self.text, re.M,
        )
        assert match is not None, "down_revision should be None for the initial migration"  # nosec B101

    def test_migration_has_upgrade_and_downgrade(self):
        assert "def upgrade() -> None:" in self.text  # nosec B101
        assert "def downgrade() -> None:" in self.text  # nosec B101

    def test_migration_creates_user_table(self):
        # users is the most critical table (every other table FKs into it).
        assert "op.create_table('users'" in self.text  # nosec B101
        # Required columns
        for col in ("'username'", "'email'", "'hashed_password'",
                    "'is_active'", "'is_admin'"):
            assert col in self.text, f"users table missing column {col}"  # nosec B101

    def test_migration_creates_all_13_model_tables(self):
        # Every model class in core.database has a __tablename__ — check
        # each one appears in a CREATE TABLE.
        expected_tables = [
            "users", "conversations", "voice_models", "job_applications",
            "interview_sessions", "analytics_events", "user_api_keys",
            "documents", "agent_sessions", "crm_configs", "integration_configs",
            "teams", "team_members", "audit_logs",
        ]
        for tbl in expected_tables:
            assert f"op.create_table('{tbl}'" in self.text, (  # nosec B101
                f"Migration does not CREATE TABLE for {tbl}"
            )

    def test_migration_creates_expected_indexes(self):
        # Spot-check a few critical indexes (FK columns + unique constraints).
        for idx in ("ix_users_username", "ix_users_email",
                    "ix_conversations_user_id", "ix_audit_logs_action",
                    "ix_job_applications_status"):
            assert idx in self.text, f"Missing index {idx}"  # nosec B101

    def test_migration_drops_all_tables_on_downgrade(self):
        # The downgrade path should call op.drop_table for every model table.
        expected_tables = [
            "users", "conversations", "voice_models", "job_applications",
            "interview_sessions", "analytics_events", "user_api_keys",
            "documents", "agent_sessions", "crm_configs", "integration_configs",
            "teams", "team_members", "audit_logs",
        ]
        for tbl in expected_tables:
            assert f"op.drop_table('{tbl}')" in self.text, (  # nosec B101
                f"downgrade() does not drop table {tbl}"
            )


# ---------------------------------------------------------------------------
# env.py wiring
# ---------------------------------------------------------------------------

class TestEnvPy:
    """migrations/env.py uses the project's Base and reads env-aware URLs."""

    def setup_method(self):
        self.env_py = (BACKEND_DIR / "migrations" / "env.py").read_text()

    def test_imports_core_database(self):
        assert "from core.database import Base" in self.env_py  # nosec B101

    def test_targets_base_metadata(self):
        assert "target_metadata = Base.metadata" in self.env_py  # nosec B101

    def test_uses_async_engine_from_config(self):
        assert "async_engine_from_config" in self.env_py  # nosec B101

    def test_resolves_url_from_env(self):
        # The env.py must NOT hardcode a connection string — it should pull
        # the URL from `core.database` (which reads env vars).
        assert "core.database" in self.env_py or "from core import database" in self.env_py  # nosec B101


# ---------------------------------------------------------------------------
# CLI-level migration operations
# ---------------------------------------------------------------------------

def _make_temp_db() -> Path:
    """Create a fresh SQLite file for a single test."""
    tmpdir = tempfile.mkdtemp(prefix="alembic_test_")
    return Path(tmpdir) / "test.db"


def _alembi_env(db_path: Path) -> dict:
    """Env vars that point alembic at the given SQLite file."""
    return {
        **os.environ,
        "DATABASE_URL": f"sqlite+aiosqlite:///{db_path}",
        "USE_SQLITE": "true",
        "FORCE_SQLITE": "true",
        "ANT_SKIP_ALEMBIC": "",  # ensure opt-out is off
    }


def _run_alembi(*args: str, env: dict) -> subprocess.CompletedProcess:
    return subprocess.run(
        [str(BACKEND_DIR / "venv" / "bin" / "alembic"), *args],
        cwd=str(BACKEND_DIR),
        env=env,
        capture_output=True,
        text=True,
        timeout=60,
    )


class TestAlembicCliOperations:
    """End-to-end: alembic upgrade / downgrade / current / stamp."""

    def setup_method(self):
        self.db_path = _make_temp_db()
        self.env = _alembi_env(self.db_path)

    def teardown_method(self):
        if self.db_path.exists():
            self.db_path.unlink()

    def _table_names(self) -> set:
        if not self.db_path.exists():
            return set()
        conn = sqlite3.connect(self.db_path)
        cur = conn.cursor()
        cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
        names = {r[0] for r in cur.fetchall()}
        conn.close()
        return names

    def _alembi_version(self) -> str | None:
        conn = sqlite3.connect(self.db_path)
        cur = conn.cursor()
        try:
            cur.execute("SELECT version_num FROM alembic_version")
            row = cur.fetchone()
            return row[0] if row else None
        except sqlite3.OperationalError:
            return None
        finally:
            conn.close()

    def test_upgrade_head_creates_all_tables(self):
        result = _run_alembi("upgrade", "head", env=self.env)
        assert result.returncode == 0, (  # nosec B101
            f"alembic upgrade head failed:\nSTDOUT:{result.stdout}\nSTDERR:{result.stderr}"
        )
        names = self._table_names()
        # 13 model tables + alembic_version
        assert len(names) == 15  # nosec B101
        for tbl in (
            "users", "conversations", "voice_models", "job_applications",
            "interview_sessions", "analytics_events", "user_api_keys",
            "documents", "agent_sessions", "crm_configs", "integration_configs",
            "teams", "team_members", "audit_logs", "alembic_version",
        ):
            assert tbl in names  # nosec B101

    def test_upgrade_head_stamps_version_table(self):
        _run_alembi("upgrade", "head", env=self.env)
        version = self._alembi_version()
        assert version is not None  # nosec B101
        # Revision ID is 12 hex chars
        assert len(version) == 12  # nosec B101
        assert all(c in "0123456789abcdef" for c in version)  # nosec B101

    def test_upgrade_is_idempotent(self):
        # First upgrade
        r1 = _run_alembi("upgrade", "head", env=self.env)
        assert r1.returncode == 0  # nosec B101
        # Second upgrade should be a no-op (no migration runs)
        r2 = _run_alembi("upgrade", "head", env=self.env)
        assert r2.returncode == 0  # nosec B101
        # "Running upgrade" only appears in r1 (alembic logs to stderr)
        assert "Running upgrade" in r1.stderr  # nosec B101
        assert "Running upgrade" not in r2.stderr  # nosec B101

    def test_current_reports_head(self):
        _run_alembi("upgrade", "head", env=self.env)
        result = _run_alembi("current", env=self.env)
        assert result.returncode == 0  # nosec B101
        assert "head" in result.stdout  # nosec B101

    def test_history_lists_initial_migration(self):
        result = _run_alembi("history", env=self.env)
        assert result.returncode == 0  # nosec B101
        assert "initial schema" in result.stdout  # nosec B101

    def test_downgrade_base_drops_all_model_tables(self):
        _run_alembi("upgrade", "head", env=self.env)
        result = _run_alembi("downgrade", "base", env=self.env)
        assert result.returncode == 0, result.stderr  # nosec B101
        names = self._table_names()
        # Only `alembic_version` should remain after downgrade to base
        assert names == {"alembic_version"}  # nosec B101

    def test_roundtrip_upgrade_downgrade_upgrade(self):
        # Up → down → up: each step should succeed and the final state
        # should match the first upgrade.
        _run_alembi("upgrade", "head", env=self.env)
        tables_after_first = self._table_names()

        _run_alembi("downgrade", "base", env=self.env)
        _run_alembi("upgrade", "head", env=self.env)
        tables_after_re_upgrade = self._table_names()

        assert tables_after_first == tables_after_re_upgrade  # nosec B101


# ---------------------------------------------------------------------------
# Fix #35 — security_question columns migration
# ---------------------------------------------------------------------------

class TestSecurityQuestionMigration:
    """Migration a1b2c3d4e5f6 adds `security_question` and
    `hashed_security_answer` to the users table. Runs alembic against
    a temp SQLite, asserts the columns exist post-upgrade, and
    confirms they are dropped on downgrade.

    The migration file is referenced by file path (not by name lookup)
    so this test continues to work even if the revision ID is
    regenerated by a future `alembic revision` run.
    """

    SECURITY_QUESTION_MIGRATION = (
        BACKEND_DIR / "migrations" / "versions" / "a1b2c3d4e5f6_add_security_question_columns.py"
    )

    def setup_method(self):
        assert self.SECURITY_QUESTION_MIGRATION.exists(), (
            f"Expected migration file missing: {self.SECURITY_QUESTION_MIGRATION}. "
            "Fix #35 Commit 1 should have created it."
        )
        self.db_path = _make_temp_db()
        self.env = _alembi_env(self.db_path)

    def teardown_method(self):
        if self.db_path.exists():
            self.db_path.unlink()

    def _column_names(self) -> set:
        """Return the set of column names on the users table."""
        if not self.db_path.exists():
            return set()
        conn = sqlite3.connect(self.db_path)
        cur = conn.cursor()
        cur.execute("PRAGMA table_info(users)")
        names = {row[1] for row in cur.fetchall()}
        conn.close()
        return names

    def _alembi_version(self) -> str | None:
        conn = sqlite3.connect(self.db_path)
        cur = conn.cursor()
        try:
            cur.execute("SELECT version_num FROM alembic_version")
            row = cur.fetchone()
            return row[0] if row else None
        except sqlite3.OperationalError:
            return None
        finally:
            conn.close()

    def test_upgrade_head_adds_security_question_columns(self):
        result = _run_alembi("upgrade", "head", env=self.env)
        assert result.returncode == 0, (  # nosec B101
            f"alembic upgrade head failed:\nSTDOUT:{result.stdout}\nSTDERR:{result.stderr}"
        )
        cols = self._column_names()
        assert "security_question" in cols  # nosec B101
        assert "hashed_security_answer" in cols  # nosec B101

    def test_upgrade_head_stamps_a1b2c3d4e5f6(self):
        result = _run_alembi("upgrade", "head", env=self.env)
        assert result.returncode == 0  # nosec B101
        version = self._alembi_version()
        # The migration chain is f78f0efa440e -> c391192d16be -> a1b2c3d4e5f6.
        # Head should land on a1b2c3d4e5f6.
        assert version == "a1b2c3d4e5f6"  # nosec B101

    def test_downgrade_one_step_drops_only_security_question_columns(self):
        _run_alembi("upgrade", "head", env=self.env)
        # Downgrade one step: c391192d16be -> a1b2c3d4e5f6 drop should remove
        # the two columns but leave the Fix #34 session columns intact.
        result = _run_alembi("downgrade", "-1", env=self.env)
        assert result.returncode == 0, result.stderr  # nosec B101
        cols = self._column_names()
        assert "security_question" not in cols  # nosec B101
        assert "hashed_security_answer" not in cols  # nosec B101
        # Fix #34 session columns are still present (c391192d16be is one rev back).
        assert "active_session_id" in cols  # nosec B101
        assert "on_new_login_pref" in cols  # nosec B101

    def test_roundtrip_upgrade_downgrade_upgrade(self):
        # Upgrade to head (a1b2c3d4e5f6) → downgrade one → upgrade to head.
        _run_alembi("upgrade", "head", env=self.env)
        cols_after_upgrade = self._column_names()
        _run_alembi("downgrade", "-1", env=self.env)
        _run_alembi("upgrade", "head", env=self.env)
        cols_after_re_upgrade = self._column_names()
        assert cols_after_upgrade == cols_after_re_upgrade  # nosec B101
        assert "security_question" in cols_after_re_upgrade  # nosec B101
        assert "hashed_security_answer" in cols_after_re_upgrade  # nosec B101


# ---------------------------------------------------------------------------
# DatabaseManager integration
# ---------------------------------------------------------------------------

class TestDatabaseManagerRunsAlembic:
    """DatabaseManager.initialize() applies alembic migrations automatically."""

    def setup_method(self):
        # Use a fresh temp dir + temp SQLite for the data dir.
        self.tmpdir = Path(tempfile.mkdtemp(prefix="dbmgr_alembic_"))
        self.tmp_db = self.tmpdir / "ainotetaker.db"
        # Point env vars at our temp DB. core.database reads DATABASE_URL,
        # USE_SQLITE, FORCE_SQLITE at import time, so we set them before
        # importing.
        os.environ["DATABASE_URL"] = f"sqlite+aiosqlite:///{self.tmp_db}"
        os.environ["USE_SQLITE"] = "true"
        os.environ["FORCE_SQLITE"] = "true"
        os.environ["ANT_SKIP_ALEMBIC"] = ""

    def teardown_method(self):
        # Clean env + files
        for var in ("DATABASE_URL", "USE_SQLITE", "FORCE_SQLITE"):
            if var in os.environ:
                del os.environ[var]
        os.environ.pop("ANT_SKIP_ALEMBIC", None)
        if self.tmp_db.exists():
            self.tmp_db.unlink()
        if self.tmpdir.exists():
            self.tmpdir.rmdir()

    def _init_db(self):
        import asyncio
        from core import database
        # Force the module to re-resolve its module-level DB URL from the
        # env vars we set in setup_method. This is safe because each test
        # creates a fresh tmpdir + tmp DB.
        database.DATABASE_URL = os.environ["DATABASE_URL"]
        database.USE_SQLITE = True
        database.FORCE_SQLITE = True
        asyncio.run(database.init_database())
        asyncio.run(database.close_database())

    def _table_names(self) -> set:
        if not self.tmp_db.exists():
            return set()
        conn = sqlite3.connect(self.tmp_db)
        cur = conn.cursor()
        cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
        names = {r[0] for r in cur.fetchall()}
        conn.close()
        return names

    def _alembi_version(self) -> str | None:
        conn = sqlite3.connect(self.tmp_db)
        cur = conn.cursor()
        try:
            cur.execute("SELECT version_num FROM alembic_version")
            return cur.fetchone()[0]
        except sqlite3.OperationalError:
            return None
        finally:
            conn.close()

    def test_init_creates_all_tables(self):
        self._init_db()
        names = self._table_names()
        assert "users" in names  # nosec B101
        assert "conversations" in names  # nosec B101
        assert "audit_logs" in names  # nosec B101
        assert "alembic_version" in names  # nosec B101
        assert len(names) == 15  # nosec B101

    def test_init_stamps_alembic_version(self):
        self._init_db()
        version = self._alembi_version()
        assert version is not None  # nosec B101
        assert len(version) == 12  # nosec B101

    def test_init_is_idempotent(self):
        # First init
        self._init_db()
        tables_first = self._table_names()
        # Second init should not change anything
        self._init_db()
        tables_second = self._table_names()
        assert tables_first == tables_second  # nosec B101


class TestAntSkipAlembicOptOut:
    """ANT_SKIP_ALEMBIC=1 bypasses the alembic step (tests can opt out)."""

    def setup_method(self):
        self.tmpdir = Path(tempfile.mkdtemp(prefix="dbmgr_skip_"))
        self.tmp_db = self.tmpdir / "ainotetaker.db"
        os.environ["DATABASE_URL"] = f"sqlite+aiosqlite:///{self.tmp_db}"
        os.environ["USE_SQLITE"] = "true"
        os.environ["FORCE_SQLITE"] = "true"
        os.environ["ANT_SKIP_ALEMBIC"] = "1"

    def teardown_method(self):
        for var in ("DATABASE_URL", "USE_SQLITE", "FORCE_SQLITE"):
            if var in os.environ:
                del os.environ[var]
        os.environ.pop("ANT_SKIP_ALEMBIC", None)
        if self.tmp_db.exists():
            self.tmp_db.unlink()
        if self.tmpdir.exists():
            self.tmpdir.rmdir()

    def test_skip_alembic_does_not_create_version_table(self):
        import asyncio
        from core import database
        database.DATABASE_URL = os.environ["DATABASE_URL"]
        database.USE_SQLITE = True
        database.FORCE_SQLITE = True
        asyncio.run(database.init_database())
        asyncio.run(database.close_database())

        conn = sqlite3.connect(self.tmp_db)
        cur = conn.cursor()
        cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
        names = {r[0] for r in cur.fetchall()}
        conn.close()

        # All 13 model tables still present (via create_all)
        assert "users" in names  # nosec B101
        assert "audit_logs" in names  # nosec B101
        # But no alembic_version table
        assert "alembic_version" not in names  # nosec B101


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
