/**
 * StudyPlanScreen — read-only view of the AI-generated study plan
 * for a given topic. The plan is generated by the backend's
 * /study-plan endpoint and rendered as a Markdown-ish list.
 */
import React, { useState, useEffect } from "react"
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  ActivityIndicator,
  TextInput,
  TouchableOpacity,
} from "react-native"
import apiService from "../services/api"

export default function StudyPlanScreen() {
  const [topic, setTopic] = useState("")
  const [plan, setPlan] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)

  const generate = async () => {
    if (!topic.trim()) return
    setLoading(true)
    setError(null)
    try {
      const result = await apiService.generateStudyPlan(topic.trim())
      setPlan(result)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <View style={styles.container}>
      <Text style={styles.title}>AI Study Plan</Text>
      <View style={styles.inputRow}>
        <TextInput
          style={styles.input}
          placeholder="Enter a topic (e.g. 'React Hooks')"
          placeholderTextColor="#64748b"
          value={topic}
          onChangeText={setTopic}
          autoCapitalize="none"
          onSubmitEditing={generate}
        />
        <TouchableOpacity
          style={styles.button}
          onPress={generate}
          disabled={loading || !topic.trim()}
        >
          {loading ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text style={styles.buttonText}>Generate</Text>
          )}
        </TouchableOpacity>
      </View>

      {error && <Text style={styles.error}>{error}</Text>}

      {plan && (
        <ScrollView style={styles.plan}>
          {plan.steps?.map((step, i) => (
            <View key={i} style={styles.step}>
              <Text style={styles.stepNumber}>{i + 1}</Text>
              <Text style={styles.stepText}>{step}</Text>
            </View>
          ))}
        </ScrollView>
      )}
    </View>
  )
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0f172a", padding: 16 },
  title: { color: "#fff", fontSize: 24, fontWeight: "700", marginBottom: 16 },
  inputRow: { flexDirection: "row", gap: 8, marginBottom: 16 },
  input: {
    flex: 1,
    backgroundColor: "#1e293b",
    color: "#fff",
    padding: 12,
    borderRadius: 8,
  },
  button: {
    backgroundColor: "#3b82f6",
    padding: 12,
    borderRadius: 8,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  buttonText: { color: "#fff", fontWeight: "600" },
  error: { color: "#f87171", marginBottom: 12 },
  plan: { flex: 1 },
  step: {
    flexDirection: "row",
    backgroundColor: "#1e293b",
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  stepNumber: {
    color: "#3b82f6",
    fontSize: 18,
    fontWeight: "700",
    marginRight: 12,
  },
  stepText: { color: "#e2e8f0", fontSize: 14, flex: 1, lineHeight: 20 },
})
